default: &default
  adapter: postgresql
  username: postgres
  password:

development:
  <<: *default
  database: livra_development
  password: postgres

test:
  <<: *default
  database: livra_test

production:
  <<: *default
  database: livra_production
